name: Deploy

on:
  push:
    tags:
      - 'v*'

env:
  RAILWAY_PROJECT_ID: 522bf8f6-23ee-45d0-89b4-03183b63e1f7

jobs:
  deploy-production:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy to Railway production
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
        run: railway up --service api --environment production --detach
